# Generated by Django 6.0.4 on 2026-05-17 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesandtransactions', '0003_roles_payment_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
