# Generated by Django 6.0.4 on 2026-05-21 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesandtransactions', '0004_orderitem_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Payment Submitted', 'Payment Submitted'), ('Payment Verified', 'Payment Verified'), ('Payment Failed', 'Payment Failed'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Deleted', 'Deleted')], default='Pending Payment', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('MenuItemID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(db_column='IsAvailable', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('vendor', models.ForeignKey(db_column='Vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='MenuItem',
            field=models.ForeignKey(blank=True, db_column='Item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesandtransactions.menuitem'),
        ),
    ]
