# Generated by Django 6.0.4 on 2026-05-28 03:58

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_relationships(apps, schema_editor):
    Ingredient = apps.get_model('supply', 'Ingredient')
    Inventory = apps.get_model('supply', 'Inventory')
    IngredientSupplier = apps.get_model('supply', 'IngredientSupplier')
    IngredientInventory = apps.get_model('supply', 'IngredientInventory')

    ingredient_supplier_links = []
    for ingredient in Ingredient.objects.exclude(supplier_id__isnull=True):
        ingredient_supplier_links.append(
            IngredientSupplier(ingredient_id=ingredient.id, supplier_id=ingredient.supplier_id)
        )
    IngredientSupplier.objects.bulk_create(ingredient_supplier_links, ignore_conflicts=True)

    ingredient_inventory_links = []
    for inventory in Inventory.objects.exclude(ingredient_id__isnull=True):
        ingredient_inventory_links.append(
            IngredientInventory(ingredient_id=inventory.ingredient_id, inventory_id=inventory.id)
        )
    IngredientInventory.objects.bulk_create(ingredient_inventory_links, ignore_conflicts=True)


def remove_copied_relationships(apps, schema_editor):
    apps.get_model('supply', 'IngredientSupplier').objects.all().delete()
    apps.get_model('supply', 'IngredientInventory').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_supplier_ingredient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ingredient')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.inventory')),
            ],
            options={
                'db_table': 'supply_ingredient_stored_in_inventory',
            },
        ),
        migrations.CreateModel(
            name='IngredientSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier')),
            ],
            options={
                'db_table': 'supply_ingredient_supplied_by',
            },
        ),
        migrations.RunPython(copy_existing_relationships, remove_copied_relationships),
        migrations.RemoveField(
            model_name='ingredient',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cafeteria_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='ingredient_id',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(related_name='inventory_records', through='supply.IngredientInventory', to='supply.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='suppliers',
            field=models.ManyToManyField(related_name='ingredients', through='supply.IngredientSupplier', to='supply.supplier'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinventory',
            constraint=models.UniqueConstraint(fields=('ingredient', 'inventory'), name='unique_ingredient_inventory'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsupplier',
            constraint=models.UniqueConstraint(fields=('ingredient', 'supplier'), name='unique_ingredient_supplier'),
        ),
    ]
