# Generated by Django 6.0.4 on 2026-05-28 04:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_remove_ingredient_inventory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('view_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='supply.cafeteria'),
        ),
        migrations.CreateModel(
            name='InventoryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.inventory')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.notification')),
            ],
            options={
                'db_table': 'supply_inventory_generates_notification',
            },
        ),
        migrations.CreateModel(
            name='IngredientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ingredient')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.notification')),
            ],
            options={
                'db_table': 'supply_ingredient_generates_notification',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='ingredients', through='supply.IngredientNotification', to='supply.notification'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='inventory_records', through='supply.InventoryNotification', to='supply.notification'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.recipe')),
            ],
            options={
                'db_table': 'supply_recipe_uses_ingredient',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='supply.RecipeIngredient', to='supply.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='inventorynotification',
            constraint=models.UniqueConstraint(fields=('inventory', 'notification'), name='unique_inventory_notification'),
        ),
        migrations.AddConstraint(
            model_name='ingredientnotification',
            constraint=models.UniqueConstraint(fields=('ingredient', 'notification'), name='unique_ingredient_notification'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
