from django.urls import path
from django.views.generic import RedirectView
from .views import (
    add_new_order,
    add_order_item,
    add_menu_item,
    delete_order,
    delete_order_item,
    delete_menu_item,
    disable_menu_item,
    edit_menu_item,
    menu_items,
    order_summary,
    payment_records,
    record_payment,
    fail_payment,
    registered_students,
    registered_vendors,
    sales_home,
    update_order_status,
    verify_payment,
)

urlpatterns = [
    path('', sales_home, name='sales_home'),
    path('orders/new/', add_new_order, name='add_new_order'),
    path('orders/<int:order_id>/', order_summary, name='order_summary'),
    path('orders/<int:order_id>/items/add/', add_order_item, name='add_order_item'),
    path('orders/<int:order_id>/items/<int:item_id>/delete/', delete_order_item, name='delete_order_item'),
    path('orders/<int:order_id>/payments/record/', record_payment, name='record_payment'),
    path('orders/<int:order_id>/payments/<int:payment_id>/verify/', verify_payment, name='verify_payment'),
    path('orders/<int:order_id>/payments/<int:payment_id>/fail/', fail_payment, name='fail_payment'),
    path('orders/<int:order_id>/status/', update_order_status, name='update_order_status'),
    path('orders/<int:order_id>/delete/', delete_order, name='delete_order'),
    path('menu-items/', menu_items, name='menu_items'),
    path('menu-items/add/', add_menu_item, name='add_menu_item'),
    path('menu-items/<int:item_id>/edit/', edit_menu_item, name='edit_menu_item'),
    path('menu-items/<int:item_id>/disable/', disable_menu_item, name='disable_menu_item'),
    path('menu-items/<int:item_id>/delete/', delete_menu_item, name='delete_menu_item'),
    path('payments/', payment_records, name='payment_records'),
    path('users/students/', registered_students, name='registered_students'),
    path('users/vendors/', registered_vendors, name='registered_vendors'),

    # Legacy redirects kept so existing bookmarks land on the clean routes.
    path('menuItems/', RedirectView.as_view(pattern_name='menu_items', permanent=False)),
    path('paymentRecords/', RedirectView.as_view(pattern_name='payment_records', permanent=False)),
    path('registeredStudents/', RedirectView.as_view(pattern_name='registered_students', permanent=False)),
    path('registeredVendors/', RedirectView.as_view(pattern_name='registered_vendors', permanent=False)),
    path('menuItems/add/', RedirectView.as_view(pattern_name='add_menu_item', permanent=False)),
    path('menuItems/<int:item_id>/edit/', RedirectView.as_view(pattern_name='edit_menu_item', permanent=False)),
    path('menuItems/<int:item_id>/disable/', RedirectView.as_view(pattern_name='disable_menu_item', permanent=False)),
    path('menuItems/<int:item_id>/delete/', RedirectView.as_view(pattern_name='delete_menu_item', permanent=False)),
    path('addNewOrder/', RedirectView.as_view(pattern_name='add_new_order', permanent=False)),
    path('addOrderItem/', RedirectView.as_view(pattern_name='sales_home', permanent=False)),
    path('addOrderItem/<int:order_id>/', RedirectView.as_view(pattern_name='add_order_item', permanent=False)),
    path('deleteOrderItem/<int:order_id>/<int:item_id>/', RedirectView.as_view(pattern_name='delete_order_item', permanent=False)),
    path('recordPayment/<int:order_id>/', RedirectView.as_view(pattern_name='record_payment', permanent=False)),
    path('orderSummary/<int:order_id>/', RedirectView.as_view(pattern_name='order_summary', permanent=False)),
    path('verifyPayment/<int:order_id>/<int:payment_id>/', RedirectView.as_view(pattern_name='verify_payment', permanent=False)),
    path('failPayment/<int:order_id>/<int:payment_id>/', RedirectView.as_view(pattern_name='fail_payment', permanent=False)),
    path('updateOrderStatus/<int:order_id>/', RedirectView.as_view(pattern_name='update_order_status', permanent=False)),
    path('deleteOrder/<int:order_id>/', RedirectView.as_view(pattern_name='delete_order', permanent=False)),
]
