# Generated by Django 6.0.4 on 2026-04-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PortionSize', models.CharField(max_length=50)),
                ('Cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcomposition.cafeteria')),
            ],
            options={
                'unique_together': {('Cafeteria', 'Name')},
            },
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('NutritionInfoID', models.AutoField(primary_key=True, serialize=False)),
                ('Calories', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Fat', models.FloatField()),
                ('Carbs', models.FloatField()),
                ('Sodium', models.FloatField()),
                ('FoodItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodcomposition.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.AutoField(primary_key=True, serialize=False)),
                ('PreparationTime', models.IntegerField()),
                ('Instructions', models.TextField()),
                ('FoodItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodcomposition.fooditem')),
                ('Ingredients', models.ManyToManyField(to='foodcomposition.ingredient')),
            ],
        ),
    ]
