# Generated by Django 6.0.4 on 2026-05-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomposition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='Capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='Location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='OperatingHours',
            field=models.CharField(default='', help_text='e.g. 7:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='QuantityUnit',
            field=models.CharField(choices=[('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('L', 'Liters (L)'), ('pcs', 'Pieces (pcs)'), ('tbsp', 'Tablespoon (tbsp)'), ('tsp', 'Teaspoon (tsp)'), ('cup', 'Cup')], default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='StorageCondition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Threshold',
            field=models.FloatField(default=0, help_text='Minimum stock before alert'),
        ),
    ]
