# Generated by Django 6.0.4 on 2026-05-21 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomposition', '0002_cafeteria_capacity_cafeteria_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Percentage', models.FloatField(help_text='Percentage between 1 and 100')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcomposition.discount'),
        ),
    ]
