# Generated by Django 6.0.4 on 2026-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ingredient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
